name = "powerball"
compatibility_date = "2026-02-10"
workers_dev = false

[[routes]]
pattern = "powerball.sirsean.me"
custom_domain = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
